### ISSUE TITLE
Rework the formal ending of the paper

### ISSUE THREAD

**Issue by horychtom** [Media-Bias-Group/llm-annotations-annomatic#25]
Right now we have discussion, conclusion, limitations and ethics. Ethics statement and limitations have some comments. Discussion is empty. Ethics is long, which is fine, but isn't directly aligned with what the ACL wants us to do in Ethics statement.

# Todo:
- [x] Check this with the ACL requirements
- [ ] Write the missing Discussion/ remove it
- [x] Rework the Ethics statement or at least align it with the comments
- [x] Rework the Limitations or at least align it with the comments
